version: '2'


services:

    web:
        build:
          context: .
          dockerfile: ./docker/Dockerfile
        image: cpanova/excentral
        command: "go run main.go"
        ports:
          - 8000:80
        volumes:
          - .:/go/src/app
        environment:
          DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
          EXCENTRAL_AFF_ID: 1
          EXCENTRAL_PID: "sdfsf"
        depends_on:
          - postgres

    # test:
    #   image: cpanova/excentral
    #   volumes:
    #     - .:/go/src/app


    postgres:
      image: "postgres:alpine"
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./volumes/postgres:/var/lib/postgresql/data
